2019/07/08 10:39:04 [error] 6#6: *1 "/usr/share/nginx/html/api/v1.0/tasks/index.html" is not found (2: No such file or directory), client: 192.168.16.1, server: localhost, request: "GET /api/v1.0/tasks/ HTTP/1.1", host: "localhost:8888"
2019/07/08 10:39:04 [error] 6#6: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.16.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888"
2019/07/08 10:39:16 [error] 6#6: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.16.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888"
2019/07/08 10:41:57 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:41:59 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:42:00 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:42:02 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:42:04 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:42:06 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:42:11 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:42:18 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:42:32 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:42:59 [emerg] 1#1: unexpected end of file, expecting "}" in /etc/nginx/conf.d/pacs.conf:27
2019/07/08 10:44:09 [error] 6#6: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.48.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888"
2019/07/08 10:44:26 [error] 6#6: *1 "/usr/share/nginx/html/api/v1.0/tasks/index.html" is not found (2: No such file or directory), client: 192.168.48.1, server: localhost, request: "GET /api/v1.0/tasks/ HTTP/1.1", host: "localhost:8888"
2019/07/08 10:44:26 [error] 6#6: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.48.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888"
2019/07/09 07:32:00 [emerg] 1#1: host not found in upstream "ui:3000" in /etc/nginx/conf.d/default.conf:2
2019/07/09 07:32:36 [error] 6#6: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET / HTTP/1.1", upstream: "http://192.168.144.3:3000/", host: "localhost:8888"
2019/07/09 07:32:39 [error] 6#6: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://192.168.144.3:3000/favicon.ico", host: "localhost:8888"
2019/07/09 07:33:30 [error] 6#6: *4 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET / HTTP/1.1", upstream: "http://192.168.144.3:3000/", host: "localhost:8888"
2019/07/09 07:36:46 [error] 6#6: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET / HTTP/1.1", upstream: "http://192.168.144.3:3000/", host: "localhost:8888"
2019/07/09 07:37:55 [error] 6#6: *7 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET /connector HTTP/1.1", upstream: "http://192.168.144.3:3000/connector", host: "localhost:8888"
2019/07/09 07:38:30 [error] 6#6: *10 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET /connector HTTP/1.1", upstream: "http://192.168.144.3:3000/connector", host: "localhost:8888"
2019/07/09 08:42:53 [error] 6#6: *13 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET /connector HTTP/1.1", upstream: "http://192.168.144.3:3000/connector", host: "localhost:8888"
2019/07/09 09:35:36 [error] 6#6: *3 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET / HTTP/1.1", upstream: "http://192.168.144.2:3000/", host: "localhost:8888"
2019/07/09 10:05:30 [error] 6#6: *26 upstream prematurely closed connection while reading response header from upstream, client: 192.168.144.1, server: _, request: "POST /sockjs-node/180/eyg2yhpq/xhr?t=1562666714151 HTTP/1.1", upstream: "http://192.168.144.2:3000/sockjs-node/180/eyg2yhpq/xhr?t=1562666714151", host: "localhost:8888", referrer: "http://localhost:8888/"
2019/07/09 10:23:42 [error] 6#6: *34 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET / HTTP/1.1", upstream: "http://192.168.144.2:3000/", host: "localhost:8888"
2019/07/09 10:25:26 [error] 6#6: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET / HTTP/1.1", upstream: "http://192.168.144.2:3000/", host: "localhost:8888"
2019/07/09 11:06:00 [error] 6#6: *34 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/conn/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/conn/", host: "localhost:8888"
2019/07/09 11:08:14 [error] 6#6: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/conn/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/conn/", host: "localhost:8888"
2019/07/09 11:08:27 [error] 6#6: *36 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/conn/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/conn/", host: "localhost:8888"
2019/07/09 11:10:03 [error] 6#6: *39 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/conn/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/conn/", host: "localhost:8888"
2019/07/09 12:16:50 [error] 6#6: *77 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/conn/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/conn/", host: "localhost:8888"
2019/07/09 12:51:42 [error] 6#6: *81 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/conn/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/conn/", host: "localhost:8888"
2019/07/09 13:38:28 [error] 6#6: *90 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/conn/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/conn/", host: "localhost:8888"
2019/07/09 13:38:29 [error] 6#6: *90 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/conn/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/conn/", host: "localhost:8888"
2019/07/18 10:26:57 [error] 6#6: *246 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/conn/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/conn/", host: "localhost:8888"
2019/07/20 03:07:04 [error] 6#6: *7896 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:15:33 [error] 7#7: *3363 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "POST /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/20 10:16:48 [error] 7#7: *3397 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:17:36 [error] 7#7: *3397 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.0.1, server: _, request: "POST /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/20 10:32:21 [error] 7#7: *3423 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "POST /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/20 10:32:42 [error] 7#7: *3491 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:33:21 [error] 7#7: *3491 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:33:35 [error] 7#7: *3491 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:34:30 [error] 7#7: *3491 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:35:57 [error] 7#7: *3496 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:38:37 [error] 7#7: *3498 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:39:22 [error] 7#7: *3498 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:39:24 [error] 7#7: *3498 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:39:44 [error] 7#7: *3498 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:40:00 [error] 7#7: *3498 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:40:02 [error] 7#7: *3498 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 10:43:17 [error] 7#7: *3509 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 11:12:45 [error] 7#7: *3514 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 11:14:08 [error] 7#7: *3516 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 11:14:53 [error] 7#7: *3516 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 11:15:11 [error] 7#7: *3516 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 11:15:23 [error] 7#7: *3516 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/20 11:28:08 [error] 7#7: *3536 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/23 11:13:10 [error] 7#7: *6746 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/get/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/get/", host: "localhost:8888"
2019/07/23 11:13:45 [error] 7#7: *6746 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/get/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/get/", host: "localhost:8888"
2019/07/23 12:19:52 [error] 7#7: *7331 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/api HTTP/1.1", upstream: "http://192.168.0.3:5000/api/api", host: "localhost:8888"
2019/07/23 12:25:04 [error] 7#7: *7344 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/23 12:27:04 [error] 7#7: *7423 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/23 12:28:11 [error] 7#7: *7477 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/23 12:32:07 [error] 7#7: *7481 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/api HTTP/1.1", upstream: "http://192.168.0.3:5000/api/api", host: "localhost:8888"
2019/07/23 12:53:59 [error] 7#7: *7625 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/23 12:54:00 [error] 7#7: *7625 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/23 12:58:45 [error] 7#7: *7636 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888"
2019/07/24 09:34:51 [error] 6#6: *3242 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.4:5000/api/v1.0/employee/add/", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/employees/1"
2019/07/24 09:34:51 [error] 6#6: *3267 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.4:5000/api/v1.0/employee/add/", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/employees/1"
2019/07/24 09:34:52 [error] 6#6: *3267 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.0.4:5000/api/v1.0/employee/add/", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/employees/1"
2019/07/24 10:31:21 [error] 6#6: *262 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/employee/update/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/employee/update/", host: "localhost:8888", referrer: "http://localhost:8888/employees/3"
2019/07/24 13:06:14 [error] 6#6: *526 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/employee/update/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/employee/update/", host: "localhost:8888", referrer: "http://localhost:8888/employees/3"
2019/07/24 13:06:17 [error] 6#6: *528 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/employee/update/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/employee/update/", host: "localhost:8888", referrer: "http://localhost:8888/employees/3"
2019/07/24 13:06:20 [error] 6#6: *526 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/employee/update/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/employee/update/", host: "localhost:8888", referrer: "http://localhost:8888/employees/3"
2019/07/24 13:28:31 [error] 6#6: *815 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/employee/update/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/employee/update/", host: "localhost:8888", referrer: "http://localhost:8888/employees/3"
2019/07/25 06:55:14 [error] 6#6: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/25 06:59:53 [error] 7#7: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://172.19.0.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/25 07:00:00 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/employee/remove/ HTTP/1.1", upstream: "http://172.19.0.4:5000/api/v1.0/employee/remove/", host: "localhost:8888", referrer: "http://localhost:8888/employees/2"
2019/07/25 08:10:03 [error] 7#7: *106 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /api/v1.0/employee/remove/ HTTP/1.1", upstream: "http://172.19.0.3:5000/api/v1.0/employee/remove/", host: "localhost:8888", referrer: "http://localhost:8888/employees/2"
2019/07/25 08:26:02 [alert] 1#1: unlink() "/var/run/nginx.pid" failed (2: No such file or directory)
2019/07/25 09:08:43 [error] 6#6: *95 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://172.24.0.3:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/25 10:25:52 [error] 6#6: *277 upstream prematurely closed connection while reading response header from upstream, client: 172.24.0.1, server: _, request: "POST /sockjs-node/334/lap4usnl/xhr?t=1564050348657 HTTP/1.1", upstream: "http://172.24.0.2:3000/sockjs-node/334/lap4usnl/xhr?t=1564050348657", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/25 10:31:27 [error] 6#6: *41 upstream prematurely closed connection while reading response header from upstream, client: 172.24.0.1, server: _, request: "POST /sockjs-node/453/iwwsnsad/xhr?t=1564050686506 HTTP/1.1", upstream: "http://172.24.0.2:3000/sockjs-node/453/iwwsnsad/xhr?t=1564050686506", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/25 10:31:53 [error] 8#8: *47 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.24.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://172.24.0.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/25 10:31:56 [error] 8#8: *56 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.24.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://172.24.0.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/25 10:31:56 [error] 8#8: *47 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://172.24.0.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/25 10:37:23 [error] 8#8: *88 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://172.24.0.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/25 10:37:23 [error] 8#8: *99 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://172.24.0.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/26 08:45:17 [emerg] 1#1: host not found in upstream "api:5000" in /etc/nginx/conf.d/default.conf:5
2019/07/26 08:45:24 [emerg] 1#1: host not found in upstream "api:5000" in /etc/nginx/conf.d/default.conf:5
2019/07/26 08:45:30 [emerg] 1#1: host not found in upstream "api:5000" in /etc/nginx/conf.d/default.conf:5
2019/07/26 08:45:37 [emerg] 1#1: host not found in upstream "api:5000" in /etc/nginx/conf.d/default.conf:5
2019/07/26 08:45:44 [emerg] 1#1: host not found in upstream "api:5000" in /etc/nginx/conf.d/default.conf:5
2019/07/26 08:45:52 [emerg] 1#1: host not found in upstream "api:5000" in /etc/nginx/conf.d/default.conf:5
2019/07/26 08:46:01 [emerg] 1#1: host not found in upstream "api:5000" in /etc/nginx/conf.d/default.conf:5
2019/07/26 08:46:13 [emerg] 1#1: host not found in upstream "api:5000" in /etc/nginx/conf.d/default.conf:5
2019/07/26 08:46:32 [emerg] 1#1: host not found in upstream "api:5000" in /etc/nginx/conf.d/default.conf:5
2019/07/26 09:50:51 [error] 6#6: *27 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.32.1, server: _, request: "GET /api/v1.0/employee/update/ HTTP/1.1", upstream: "http://192.168.32.4:5000/api/v1.0/employee/update/", host: "localhost:8888", referrer: "http://localhost:8888/employees/3"
2019/07/26 09:50:55 [error] 6#6: *31 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.32.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.32.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/26 10:23:55 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.48.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/26 10:23:58 [error] 7#7: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.48.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/26 10:24:00 [error] 7#7: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.48.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/26 10:24:02 [error] 7#7: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: _, request: "GET /api/v1.0/employee/remove/ HTTP/1.1", upstream: "http://192.168.48.4:5000/api/v1.0/employee/remove/", host: "localhost:8888", referrer: "http://localhost:8888/employees/2"
2019/07/26 10:24:02 [error] 7#7: *63 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: _, request: "GET /api/v1.0/employee/remove/ HTTP/1.1", upstream: "http://192.168.48.4:5000/api/v1.0/employee/remove/", host: "localhost:8888", referrer: "http://localhost:8888/employees/2"
2019/07/26 10:25:20 [error] 7#7: *20 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.64.1, server: _, request: "GET /api/v1.0/employee/remove/ HTTP/1.1", upstream: "http://192.168.64.4:5000/api/v1.0/employee/remove/", host: "localhost:8888", referrer: "http://localhost:8888/employees/2"
2019/07/26 10:25:21 [error] 7#7: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.64.1, server: _, request: "GET /api/v1.0/employee/remove/ HTTP/1.1", upstream: "http://192.168.64.4:5000/api/v1.0/employee/remove/", host: "localhost:8888", referrer: "http://localhost:8888/employees/2"
2019/07/26 10:25:25 [error] 7#7: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.64.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.64.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/26 10:25:59 [error] 7#7: *57 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.64.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.64.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/26 10:30:50 [error] 6#6: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.80.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/26 10:30:52 [error] 6#6: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.80.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/26 10:30:54 [error] 6#6: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: _, request: "GET /api/v1.0/employee/add/ HTTP/1.1", upstream: "http://192.168.80.4:5000/api/v1.0/employee/add/", host: "localhost:8888", referrer: "http://localhost:8888/employees/1"
2019/07/29 05:26:56 [error] 6#6: *2938 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.80.1, server: _, request: "GET /api/v1.0/employee/update/ HTTP/1.1", upstream: "http://192.168.80.4:5000/api/v1.0/employee/update/", host: "localhost:8888", referrer: "http://localhost:8888/employees/3"
2019/07/29 05:27:03 [error] 6#6: *2941 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.80.1, server: _, request: "GET /api/v1.0/employee/update/ HTTP/1.1", upstream: "http://192.168.80.4:5000/api/v1.0/employee/update/", host: "localhost:8888", referrer: "http://localhost:8888/employees/3"
2019/07/29 05:27:14 [error] 6#6: *2908 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.80.1, server: _, request: "GET /api/v1.0/employee/update/ HTTP/1.1", upstream: "http://192.168.80.4:5000/api/v1.0/employee/update/", host: "localhost:8888", referrer: "http://localhost:8888/employees/3"
2019/07/30 19:01:55 [error] 6#6: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:3000/", host: "localhost:8888"
2019/07/30 19:01:58 [error] 6#6: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:8888"
2019/07/30 19:02:12 [error] 6#6: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:3000/", host: "localhost:8888"
2019/07/30 19:13:24 [error] 6#6: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:3000/", host: "localhost:8888"
2019/07/30 19:30:08 [error] 6#6: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.18.0.2:3000/", host: "localhost:8888"
2019/08/21 14:18:13 [error] 6#6: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.18.0.2:3000/", host: "localhost:7777"
2019/08/21 14:18:16 [error] 6#6: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.2:3000/favicon.ico", host: "localhost:7777"
